language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS orm_odm_tests;create database IF NOT EXISTS doctrine_tests;'; fi"
  - composer install --prefer-source --dev

script: phpunit -c tests/phpunit_doctrine_dbal.xml.dist

notifications:
  email: "maximilian.berghoff@gmx.de"

matrix:
  allow_failures:
#    - env: TRANSPORT=midgard_sqlite
#    - env: TRANSPORT=midgard_mysql